In [1]:
import numpy as np

class QRdecompose:
    '''Class to perform QR decomposition'''
    
    def __init__(self,A,tol=1.0e-10):
        self.A0=A
        self.N=A.shape[0]
        self.tol=tol
        
        [self.evals,self.evecs]=self.qr_steps()
        
        
    def qr_steps(self):
        '''Perform the QR steps until the off-diagonal elements are small enough'''
        V=np.identity(self.N)
        D=np.copy(self.A0)
        
        maxOffDiag=self.tol*100 # To get us into the loop
        
        while (maxOffDiag > self.tol):
        
            Q,R=self.qr_decomp(D)
            D=np.matmul(R,Q)
            V=np.matmul(V,Q)
        
            diagD=np.diag(np.diagonal(D))
            maxOffDiag=np.amax(D-diagD)

        return np.diagonal(D),V
        
        
    def qr_decomp(self,A):
        '''perform the QR decomposition'''
        
        Q=np.zeros((self.N,self.N))
        R=np.zeros((self.N,self.N))
        
        for ii in range(0,self.N):
            
            # Calculate u_i
            u=A[:,ii]
            for jj in range(0,ii):
                u-=np.matmul(Q[:,jj],A[:,ii])*Q[:,jj]
            
            Q[:,ii]=u/np.linalg.norm(u)
            
            # Now populate row of R
            R[ii,ii]=np.linalg.norm(u)
            if ii<self.N:
                R[ii,ii+1:]=np.matmul(Q[:,ii],A[:,ii+1:])
                
        return Q,R
            
    
        

In [2]:
# Simple example

A=np.array([[1,4,8,4],[4,2,3,7],[8,3,6,9],[4,7,9,2]],dtype='float')

eigA=QRdecompose(A)

np.set_printoptions(precision=4,suppress=True)
print(eigA.evals)
print()
print(eigA.evecs)
print()
print(np.transpose(eigA.evecs) @ A @ eigA.evecs)


[21. -8. -3.  1.]

[[ 0.4315 -0.3836 -0.7746 -0.2582]
 [ 0.3836  0.4315 -0.2582  0.7746]
 [ 0.6233  0.5274  0.2582 -0.5164]
 [ 0.5274 -0.6233  0.5164  0.2582]]

[[21.  0.  0. -0.]
 [ 0. -8.  0.  0.]
 [ 0.  0. -3. -0.]
 [-0.  0. -0.  1.]]


In [5]:
# Random (symmetric) matrix
nMatrix=20
A=np.random.rand(nMatrix,nMatrix)
A=A + A.T - np.diag(A.diagonal())
eigA=QRdecompose(A)

print(eigA.evals)
print(np.linalg.eigvalsh(A))

[19.3292 -3.7483 -3.2084 -2.7838  2.5215 -2.4383 -2.2144  2.1841  1.92
 -1.7929 -1.5853  1.3447 -1.2433 -1.168  -0.7483  0.7313  0.4146  0.3224
 -0.1816  0.0314]
[-3.7483 -3.2084 -2.7838 -2.4383 -2.2144 -1.7929 -1.5853 -1.2433 -1.168
 -0.7483 -0.1816  0.0314  0.3224  0.4146  0.7313  1.3447  1.92    2.1841
  2.5215 19.3292]
