In [1]:
import numpy as np

def jacobi_solve(A,b,x0,tol=1.0e-10,nTolMax=1000):
    '''Solves linear system with Jacobi iterative method'''
    
    N=len(b)
    x=x0

    D=np.diag(np.diagonal(A))
    LU=A-D
        
    for n in range(nTolMax):
        
        x=np.matmul(np.linalg.inv(D),(b - np.matmul(LU,x0)))
        
        if max(abs(x-x0))< tol:
            return x
        
        x0=x
        print(x)
    
    
    raise("Did not converge!")
    
    return x

    

In [4]:
# Random matrix
nMatrix=100
A=np.random.rand(nMatrix,nMatrix)
b=np.random.rand(nMatrix)
x0=np.random.rand(nMatrix)

# Lets ensure that it is strictly diagonally dominant
A+=nMatrix*np.identity(nMatrix)

# Now we can solve
x=jacobi_solve(A,b,x0)

# Lets make sure it worked!
print()
print('Residual (should be zero): ',np.matmul(A,x)-b)


[-0.25858139 -0.23125498 -0.23795368 -0.2618332  -0.24998651 -0.27673893
 -0.22742263 -0.26901418 -0.25625746 -0.23163853 -0.22128852 -0.25069882
 -0.23833114 -0.26460388 -0.27804586 -0.22315563 -0.25778434 -0.24705061
 -0.25007757 -0.27125891 -0.27038314 -0.25256373 -0.22242368 -0.26136422
 -0.23508927 -0.25837925 -0.25727737 -0.24042595 -0.25709275 -0.26424523
 -0.25742761 -0.26664679 -0.24732186 -0.24034237 -0.26183082 -0.25638966
 -0.22509033 -0.25836081 -0.25399353 -0.24589133 -0.21977902 -0.23653084
 -0.27522036 -0.25245915 -0.271881   -0.23548875 -0.26718182 -0.24287921
 -0.28769056 -0.26302365 -0.24515283 -0.28409649 -0.26207455 -0.24244916
 -0.25970041 -0.22099702 -0.23726279 -0.24468525 -0.25572255 -0.26663725
 -0.19491609 -0.2573848  -0.25362581 -0.2777924  -0.2278464  -0.26139247
 -0.28341467 -0.27101083 -0.24719266 -0.27846435 -0.29704092 -0.28421946
 -0.25613579 -0.25652018 -0.23350627 -0.25680778 -0.25829562 -0.25332121
 -0.2429889  -0.24638988 -0.25201203 -0.26413813 -0

In [5]:
# Example where it will not converge (from wikipedia)
A=np.array([[29,2,1],[2,6,1],[1,1,0.2]])
b=np.random.rand(3)
x0=np.random.rand(3)

# Try to solve
x=jacobi_solve(A,b,x0)



[-0.05266903 -0.08289867 -1.10233408]
[0.05952036 0.22558504 4.72759113]
[-0.16278628 -0.78346562  2.62422565]
[-0.02066674 -0.3588025   8.78101219]
[-0.26225683 -1.43230677  5.94709883]
[-0.09050091 -0.87945784 12.52257066]
[-0.35536883 -2.03262179  8.89954639]
[-0.15090841 -1.34049511 15.98970574]
[-0.44312954 -2.5903418  11.50677022]
[-0.20234923 -1.74577884 19.21710934]
[-0.52646871 -3.11109546 13.79039299]
[-0.2451808  -2.09860291 22.23757353]
[-0.60628996 -3.60022897 15.76867118]
[-0.27966394 -2.40170886 25.08234729]
[-0.68348174 -4.06286355 17.45661665]
[-0.30596312 -2.65730251 27.78147913]
[-0.75892811 -4.50395246 18.86608081]
[-0.32414541 -2.86706442 30.3641555 ]
[-0.83351958 -4.92833776 20.00580178]
[-0.33417818 -3.03215409 32.85903934]
[-0.90816456 -5.34080748 20.88141399]
[-0.33592552 -3.1532078  35.29461283]
[-0.98380132 -5.74615395 21.49541922]
[-0.32914318 -3.23032975 37.69952899]
[-1.06141071 -6.14923409 21.8471173 ]
[-0.31347207 -3.2630763  40.10297661]
[-1.14202983 -6

TypeError: exceptions must derive from BaseException