In [11]:
import numpy as np

def jacobi_solve(A,b,x0,tol=1.0e-10,nTolMax=1000):
    '''Solves linear system with Jacobi iterative method'''
    
    N=len(b)
    x=x0

    D=np.diag(np.diagonal(A))
    LU=A-D
        
    for n in range(nTolMax):
        
        x=np.matmul(np.linalg.inv(D),(b - np.matmul(LU,x0)))
        
        if max(abs(x-x0))< tol:
            return x
        
        x0=x
        print(x)
    
    
    print("ERROR: Did not converge!")
    return x

    

In [12]:
# Random matrix
nMatrix=3
A=np.random.rand(nMatrix,nMatrix)
b=np.random.rand(nMatrix)
x0=np.random.rand(nMatrix)

# Lets ensure that it is strictly diagonally dominant
A+=nMatrix*np.identity(nMatrix)

# Now we can solve
x=jacobi_solve(A,b,x0)

# Lets make sure it worked!
print()
print('Residual (should be zero): ',np.matmul(A,x)-b)


[ 0.02398243 -0.06965981  0.04646579]
[0.15676091 0.02371482 0.08635008]
[ 0.14032894 -0.00491681  0.07072699]
[ 0.14601216 -0.00050761  0.07297277]
[ 0.14516738 -0.00177675  0.07229652]
[ 0.14541621 -0.00156035  0.07240826]
[ 0.14537446 -0.00161701  0.07237823]
[ 0.14538553 -0.00160659  0.07238364]
[ 0.14538352 -0.00160914  0.07238229]
[ 0.14538402 -0.00160865  0.07238255]
[ 0.14538392 -0.00160877  0.07238249]
[ 0.14538394 -0.00160874  0.0723825 ]
[ 0.14538394 -0.00160875  0.07238249]
[ 0.14538394 -0.00160875  0.0723825 ]
[ 0.14538394 -0.00160875  0.0723825 ]

Residual (should be zero):  [3.48711060e-11 3.94539817e-11 1.92348915e-11]


In [13]:
# Example where it will not converge (from wikipedia)
A=np.array([[29,2,1],[2,6,1],[1,1,0.2]])
b=np.random.rand(3)
x0=np.random.rand(3)

# Try to solve
x=jacobi_solve(A,b,x0)



[-0.00775489 -0.22729587 -3.20231969]
[0.14465413 0.63232861 2.77005724]
[-0.12057435 -0.41387055 -2.29011028]
[0.12606585 0.5179002  4.26702793]
[-0.16430242 -0.65716957 -1.62502681]
[0.11991118 0.42162897 5.70216336]
[-0.20715045 -0.89430725 -1.11289734]
[0.11860587 0.35055674 7.10209194]
[-0.25052232 -1.12719358 -0.75100961]
[0.1221881  0.30469941 8.48338289]
[-0.29499046 -1.35860282 -0.53963414]
[0.13085855 0.28429288 9.86276982]
[-0.34114818 -1.59139079 -0.48095373]
[ 0.14488943  0.28989872 11.25749828]
[-0.38962888 -1.82852249 -0.57913732]
[ 0.16462899  0.32242288 12.68556027]
[-0.44111544 -2.07311267 -0.8404559 ]
[ 0.19050826  0.38313816 14.16594399]
[-0.49635042 -2.32846972 -1.27342869]
[ 0.22304919  0.47371195 15.71890409]
[-0.55614723 -2.59814338 -1.88900228]
[ 0.26287404  0.59623982 17.36625646]
[-0.62140268 -2.88597706 -2.70076592]
[ 0.31071649  0.75328558 19.13170214]
[-0.69311086 -3.19616549 -3.72520695]
[ 0.36743435  0.94792848 21.04118518]
[-0.77237875 -3.53331861 -4.98